version: "3.9"
name: developing
services:

    php:
        build:
            context: .
            dockerfile: "Docker/Dockerfile"
        working_dir: "/var/www/html"
        command: "php artisan serve --host=0.0.0.0 --port=80"
        volumes:
            - "./:/var/www/html"
        ports:
            - "80:80"


    composer:
        image: composer
        volumes:
            - ".:/app"
